### ISSUE TITLE
Corrección de tareas:

### ISSUE THREAD

**Issue by JosiasVasquez** [IsaacArandia04/Tareas_Tech4Inclusion#1]
### En todas tus tareas:

Tienes una confusión con la etiqueta p, la primera vez que la utilizas lo haces bien, pero luego le pones p2, p3 p4 etc.

Para todos los párrafos utilizas solo `<p>`

La primera lista de la tercera tarea mesclaste dos tipos de lista de una forma incorrecta, utiliza solo una lista descriptiva o una lista ordenada.

Todo excelente, solo como recomendación, fíjate bien en lo que escribes, o utiliza un corrector ortográfico para corregir errores de tipéo.

**Comment by IsaacArandia04** [comment]
Entendido instructor, muchas gracias por sus observaciones, las tendre mas en cuenta y practicare mucho mas.
